# Generated by Django 3.2.5 on 2021-10-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('fat_count', models.IntegerField(default=0)),
                ('stupid_count', models.IntegerField(default=0)),
                ('dumb_count', models.IntegerField(default=0)),
            ],
        ),
    ]
